"""Augment the training frame with disclosed synthetic rows (risk & yield tasks).

Synthetic rows are generated by the Gaussian copula over the continuous block
(features + the continuous risk score + yield). Categorical context
(province/crop/season) is sampled from empirical marginals. The synthetic
``risk_level`` label is derived by banding the generated risk score with
thresholds learned from the real score/level mapping. Price-direction is a
temporal target and is intentionally NOT augmented (documented limitation).
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from varimi.synth.copula import GaussianCopulaSynthesizer

CONTINUOUS = [
    "rainfall_mm",
    "ndvi_proxy_0_1",
    "pest_incidents_reported",
    "irrigation_coverage_pct",
    "input_availability_score_0_100",
    "climate_crop_risk_score_0_100",
    "estimated_yield_t_per_ha",
]
CATEGORICAL = ["province", "crop", "season"]
INTEGER = ("pest_incidents_reported",)


def infer_risk_thresholds(df: pd.DataFrame) -> tuple[float, float]:
    """Learn (low_cut, med_cut) score thresholds from real score/level pairs."""
    score = "climate_crop_risk_score_0_100"
    low_cut = df.loc[df["risk_level"] == "Low", score].max()
    med_cut = df.loc[df["risk_level"] == "Medium", score].max()
    if not (np.isfinite(low_cut) and np.isfinite(med_cut)) or low_cut >= med_cut:
        low_cut, med_cut = np.quantile(df[score], [1 / 3, 2 / 3])
    return float(low_cut), float(med_cut)


def band_risk(scores: np.ndarray, low_cut: float, med_cut: float) -> np.ndarray:
    out = np.where(scores <= low_cut, "Low", np.where(scores <= med_cut, "Medium", "High"))
    return out.astype(object)


def make_synthetic(df: pd.DataFrame, n: int, seed: int = 42) -> pd.DataFrame:
    """Return ``n`` synthetic rows with engineered ``risk_level`` labels."""
    synth = GaussianCopulaSynthesizer(CONTINUOUS, CATEGORICAL, INTEGER, seed=seed)
    synth.fit(df)
    sampled = synth.sample(n)
    low_cut, med_cut = infer_risk_thresholds(df)
    sampled["risk_level"] = band_risk(
        sampled["climate_crop_risk_score_0_100"].to_numpy(), low_cut, med_cut
    )
    sampled["is_synthetic"] = True
    return sampled


def augment_training_frame(
    train_df: pd.DataFrame, ratio: float = 1.0, seed: int = 42
) -> pd.DataFrame:
    """Concatenate real training rows with ``ratio * len`` synthetic rows."""
    n_synth = int(round(len(train_df) * ratio))
    synth = make_synthetic(train_df, n_synth, seed=seed)
    real = train_df.copy()
    real["is_synthetic"] = False
    shared = [c for c in real.columns if c in synth.columns]
    return pd.concat([real[shared], synth[shared]], ignore_index=True)
